### ISSUE TITLE
[Chore] Node version conflict

### ISSUE THREAD

**Issue by malparty** [pnbao/nb-google-keywords-be#4]
## Issue

- The `README.md` file requires Node `v20.8.1 (LTS)`.
- The `.nvmrc` file requires Node `18`.

## Expected

When a project contains a `.nvmrc` (or better, a `.tool-versions`) file, ensure to have the same versions in the `README.md` file, or remove the redundant information from the `README.md` file.

**Comment by pnbao** [comment]
@malparty thank you for pointing that out, will be updated after [the PR #1](https://github.com/pnbao/nb-google-keywords-fe/pull/1)
