### ISSUE TITLE
[Bug] Next.js navigation is not consistent

### ISSUE THREAD

**Issue by malparty** [pnbao/nb-google-keywords-be#5]
## Issue

Then just logged in (with no prior keywords), a message invites the user to go to the keywords page: "Let's start by uploading some keywords in the Keywords page".

When clicking on the `Keywords` link, the whole application is entirely refreshed.

When clicking on the navigation item `Keywords` (in the left sidebar), the navigation uses client-side routing and fetches the server using XHR requests (which results in a much better user experience).

## Expected

In a Next.js app, page navigation be done with the [Link component](https://nextjs.org/docs/app/api-reference/components/link) provided by Next.js to ensure consistent and optimized navigation.

**Comment by pnbao** [comment]
@malparty thank you for figuring this out. I have updated in [the #2 PR](https://github.com/pnbao/nb-google-keywords-fe/pull/2)
