### ISSUE TITLE
[Bug] The names of some keywords are blank randomly

### ISSUE THREAD

**Issue by malparty** [pnbao/nb-google-keywords-be#6]
## Issue

When refreshing the list of keywords, some keywords are rendered with blank names.

Here is an example of a blank keyword: https://nb-google-search-result-fe-844227fc01f0.herokuapp.com/dashboard/keywords/e6dc7aba-605b-4590-9c44-7629b99dc70e/view

And here is a screenshot of the keyword list:

![image](https://github.com/pnbao/nb-google-keywords-be/assets/77609814/ad485f4d-d534-4823-ad9d-65819de3bc3d)

## Expected

The name of the keywords should always be displayed.

**Comment by pnbao** [comment]
Hello @malparty. Can you send me the test file of this case? I will have a better investigation with that error file.

**Comment by malparty** [comment]
@pnbao hm... I think I found the issue, I unadvertidly added a "comma" to the end of each line.


This is the file used when the issue occurred: 

[CSV_OK_vertical.csv](https://github.com/pnbao/nb-google-keywords-be/files/15414983/CSV_OK_vertical.csv)


I just made a second test with a file "free" from these commas and it is working. 

While I made the mistake in that case, I will close the issue 👍 Feel free to add a condition to not parse "blank" keywords though 😇
