### ISSUE TITLE
[Bug] Link count is not working

### ISSUE THREAD

**Issue by malparty** [pnbao/nb-google-keywords-be#7]
## Issue

The link count is not working as it shows 4 or 5 links to most keywords.

## Expected:

All keywords should have more than 5 links because the footer already contains 5 links and the Google logo on the header is also a link. Then any result should count for at least 1 additional link (though it is often more).

```
<span id="footer">
	<div>
		<div id="WqQANb">
			<a href="/intl/en/ads/">Advertising</a>
			<a href="/services/">Business Solutions</a>
			<a href="/intl/en/about.html">About Google</a>
		</div>
	</div>
	<p style="font-size:8pt;color:#70757a">
		© 2024 - <a href="/intl/en/policies/privacy/">Privacy</a>
		- <a href="/intl/en/policies/terms/">Terms</a>
	</p>
</span>
```

**Comment by pnbao** [comment]
Hello @malparty

I only [count the links](https://github.com/pnbao/nb-google-keywords-be/blob/d9d267d083788b0573b198f5fac5055c2104a014/services/scraper.go#L27C3-L32C5) that start with the `https`, so all href link as local assets is not counted.

**Comment by malparty** [comment]
Well noted. What about renaming it in the UI as `Absolute links`?

**Comment by pnbao** [comment]
Sure. `Absolute links` will better describe which data this tool is scrapping.
